/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package cn.nwafulive.zq.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENTIALSTATEMENT = 4;
  public int JJTASSIGNMENTSTATEMENT = 5;
  public int JJTCONDITIONALSTATEMENT = 6;
  public int JJTCONDITION = 7;
  public int JJTRELATIONSYMBOL = 8;
  public int JJTOPERATOR = 9;
  public int JJTLOOPSTATEMENT = 10;
  public int JJTVARIABLEDECLARE = 11;
  public int JJTEXPRESSION = 12;
  public int JJTADDITIVEEXPRESSION = 13;
  public int JJTMULTIPLICATIVEEXPRESSION = 14;
  public int JJTUNARYEXPRESSION = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTINTEGER = 17;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "StatementBlock",
    "Statement",
    "SequentialStatement",
    "AssignmentStatement",
    "ConditionalStatement",
    "Condition",
    "RelationSymbol",
    "Operator",
    "LoopStatement",
    "VariableDeclare",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=5f4b15645ea88297145bcfbac3cb22eb (do not edit this line) */
